version: '3.4'

services:
  catalogdb:
    image: mongo

  apimongodb:
    image: ${DOCKER_REGISTRY-}apimongodb
    build:
      context: .
      dockerfile: APIMongoDB/Dockerfile

volumes:
  mongo_data:

